language: python
python:
  - 3.8
install:
 - pip install -q -r requirements-dev.txt 
 - pip install -q codecov
script:
 - pip install senderscore
 - flake8
 - pytest --cov=senderscore
after_success:
 - codecov
